import styled from "styled-components";

export const StyledLoader = styled("div")`
  @keyframes ldio-kzhmg3skfv {
    0% {
      transform: translate(2px, 2px);
    }
    33.33% {
      transform: translate(102px, 2px);
    }
    66.66% {
      transform: translate(42px, 102px);
    }
    100% {
      transform: translate(2px, 2px);
    }
  }

  .ldio-kzhmg3skfv > div {
    transform: scale(0.8);
    transform-origin: 100px 100px;
  }

  .ldio-kzhmg3skfv > div > div {
    animation: ldio-kzhmg3skfv 1.5384615384615383s linear infinite;
    position: absolute;
  }

  .ldio-kzhmg3skfv > div > div div:nth-child(1) {
    width: 72px;
    height: 72px;
    border-radius: 50%;
    border: 12px solid #5e6fa3;
    background: #d9dbee;
  }

  .ldio-kzhmg3skfv > div > div div:nth-child(2) {
    width: 17px;
    height: 51px;
    transform: rotate(-45deg);
    background: #5e6fa3;
    border-radius: 0 0 8px 8px;
    position: absolute;
    top: 68px;
    left: 85px;
  }
  .loadingio-spinner-magnify-jikjqrh9nt {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: #f1f2f3;
    margin: auto;
  }
  .ldio-kzhmg3skfv {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0;
  }
  .ldio-kzhmg3skfv div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
`;
